services:
  nginx:
    image: nginx:latest
    # 开机启动
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /Users/zouyl/env/docker-compose-env/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/zouyl/env/docker-compose-env/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /Users/zouyl/env/docker-compose-env/volumes/nginx/logs:/var/log/nginx
      - /Users/zouyl/env/docker-compose-env/volumes/nginx/html:/usr/share/nginx/html
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /Users/zouyl/env/docker-compose-env/volumes/redis/data:/data
      - /Users/zouyl/env/docker-compose-env/volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - /Users/zouyl/env/docker-compose-env/volumes/mysql/data:/var/lib/mysql
      - /Users/zouyl/env/docker-compose-env/volumes/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /Users/zouyl/env/docker-compose-env/volumes/mysql/logs:/var/log/mysql

  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /Users/zouyl/env/docker-compose-env/volumes/php:/var/www/html
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
